# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```


In [6]:
import pandas as pd

df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
df.head()

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  AGECPOXR  \
1   128521     12852     2         NaN  235.916956     1031  2017       NaN   
2    10741      1074     2         NaN  957.353840     1068  2017       NaN   
3   220011     22001     2         NaN  189.611299     1050  2017       NaN   
4    86131      8613     1  675.430817  333.447418     1040  2017       NaN   
5   227141     22714     1  482.617748  278.768063     1008  2017       NaN   

   HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
1         2       1  ...                        NaN      NaN      NaN   
2         2       1  ...                        NaN      NaN      NaN   
3         2       3  ...                        NaN      NaN      NaN   
4         2       1  ...                        NaN      NaN      NaN   
5         2       1  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          NaN          NaN  
4      NaN      NaN      NaN          1.0          2.0  
5      NaN      NaN      NaN          2.0          1.0  

[5 rows x 453 columns]

In [7]:
# 'EDUC1' stands for the level of education of mother categories
level_of_education = df['EDUC1']
level_of_education.head()

1    4
2    3
3    3
4    4
5    1
Name: EDUC1, dtype: int64

In [13]:
# 1 for "less than high school"
# 2 for "high school"
# 3 for "more than high school but not college"
# 4 for "college"
import numpy as np
print(len(df[df['EDUC1'] == 1]))
print(len(df[df['EDUC1'] == 2]))
print(len(df[df['EDUC1'] == 3]))
print(len(df[df['EDUC1'] == 4]))
print((len(df[df['EDUC1'] == 1]) +
      len(df[df['EDUC1'] == 2]) +
      len(df[df['EDUC1'] == 3]) +
      len(df[df['EDUC1'] == 4])) == len(df))

2904
4906
6999
13656
True


In [14]:
def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE
    result = {'less than high school':0,
             'high school':0,
             'more than high school but not college':0,
             'college':0}
    result['less than high school'] = len(df[df['EDUC1'] == 1])/len(df)
    result['high school'] = len(df[df['EDUC1'] == 2])/len(df)
    result['more than high school but not college'] = len(df[df['EDUC1'] == 3])/len(df)
    result['college'] = len(df[df['EDUC1'] == 4])/len(df)
    return result

In [15]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [16]:
df.columns

Index(['SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D', 'STRATUM', 'YEAR',
       'AGECPOXR', 'HAD_CPOX', 'AGEGRP',
       ...
       'XVRCTY2', 'XVRCTY3', 'XVRCTY4', 'XVRCTY5', 'XVRCTY6', 'XVRCTY7',
       'XVRCTY8', 'XVRCTY9', 'INS_STAT2_I', 'INS_BREAK_I'],
      dtype='object', length=453)

In [25]:
# CBF_01 : Child breastfed or not
#   1 : YES ??? ; 2 : NO ???
#   77 : DON'T KNOW; 99 : REFUSED
# P_NUMFLU : number of seasonal flu-containing vaccinations by 36 months of age


# df[['CBF_01', 'P_NUMFLU']].head()
print(df['CBF_01'].unique())
print(df['P_NUMFLU'].unique())
df['P_NUMFLU'].head()

[ 1  2 99 77]
[nan  3.  0.  2.  1.  4.  5.  6.]


1    NaN
2    NaN
3    NaN
4    3.0
5    0.0
Name: P_NUMFLU, dtype: float64

In [55]:
# replace NaN values with 0's as it won't affect the calculation
df['P_NUMFLU'].fillna(0, inplace=True)

data = df[['CBF_01', 'P_NUMFLU']]
# 

print(data['CBF_01'].unique())
fed = data[data['CBF_01'] == 1].dropna()
not_fed = data[data['CBF_01'] == 2].dropna()
fed.head()

[ 1  2 99 77]


CBF_01  P_NUMFLU
1       1       0.0
5       1       0.0
7       1       0.0
8       1       0.0
9       1       0.0

In [58]:
print(np.sum(fed['P_NUMFLU'])/len(fed))

1.0298833518816206


In [61]:
def average_influenza_doses():
    # YOUR CODE HERE
    import numpy as np
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv', index_col = 0)
    
    # filtered DataFrame with just the 2 variables
    data = df[['CBF_01', 'P_NUMFLU']]
    
    # DataFrame for the children having been breastfed
    fed = data[data['CBF_01'] == 1].dropna()
    
    # DataFrame for the children not having been breastfed
    not_fed = data[data['CBF_01'] == 2].dropna()
    
    return (np.sum(fed['P_NUMFLU'])/len(fed), np.sum(not_fed['P_NUMFLU'])/len(not_fed))

In [62]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [64]:
# SEX : sex of child
# 1 => male
# 2 => female
print(df['SEX'].unique())

# HAD_CPOX
# 1 => Yes
# 2 => No
print(df['HAD_CPOX'].unique())

# P_NUMVRC
print(df['P_NUMVRC'].unique())

[1 2]
[ 2  1 77 99]
[nan  1.  0.  2.  3.]


In [76]:
data = df[['HAD_CPOX', 'P_NUMVRC', 'SEX']]

# fill the NaN values in 'P_NUMVRC' with 0's
data['P_NUMVRC'].fillna(0, inplace=True)

# DataFrame with all children vaccinated against varicella
vaccinated = data[data['P_NUMVRC'] >= 1]
vaccinated.head()

HAD_CPOX  P_NUMVRC  SEX
4          2       1.0    2
7          2       1.0    2
11         2       1.0    1
13         2       1.0    1
17         2       2.0    1

In [87]:
vac_cpox = vaccinated[vaccinated['HAD_CPOX'] == 1]
vac_ncpox = vaccinated[vaccinated['HAD_CPOX'] == 2]

print(len(vac_cpox[vac_cpox['SEX'] == 2])/len(vac_ncpox[vac_ncpox['SEX'] == 2]))

0.0077918259335489565


In [92]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    import pandas as pd
    import numpy as np
    
    df = pd.read_csv("assets/NISPUF17.csv", index_col = 0)
    
    data = df[['SEX', 'HAD_CPOX', 'P_NUMVRC']]
    
    # children vaccinated against varicella and we get 'HAD_CPOX' values to
    # be only 1 or 2
    vaccinated = data[(data['P_NUMVRC'] > 0) & (data['HAD_CPOX'] < 3)]
    
    # fill the NaN values with 0's
    vaccinated['P_NUMVRC'].fillna(0, inplace=True)
    
    # children who caught chicken pox despite the vaccine
    c_pox = vaccinated[vaccinated['HAD_CPOX'] == 1]
    # children who didn't catch chicken pox AND got vaccinated
    nc_pox = vaccinated[vaccinated['HAD_CPOX'] == 2]
    
    result = {'male':0,
             'female':0}
    
    # male => 1
    result['male'] = len(c_pox[c_pox['SEX'] == 1])/len(nc_pox[nc_pox['SEX'] == 1])
    # female => 2
    result['female'] = len(c_pox[c_pox['SEX'] == 2])/len(nc_pox[nc_pox['SEX'] == 2])
    
    return result

In [93]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


0.0077918259335489565


## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [100]:
df = pd.read_csv("assets/NISPUF17.csv", index_col = 0)
df = df[['HAD_CPOX', 'P_NUMVRC']]
df.head()

HAD_CPOX  P_NUMVRC
1         2       NaN
2         2       NaN
3         2       NaN
4         2       1.0
5         2       0.0

In [101]:
df = df[df['HAD_CPOX'] < 3]
df.head()

HAD_CPOX  P_NUMVRC
1         2       NaN
2         2       NaN
3         2       NaN
4         2       1.0
5         2       0.0

In [106]:
df = df.dropna()
df.head()

HAD_CPOX  P_NUMVRC
4         2       1.0
5         2       0.0
7         2       1.0
8         2       0.0
9         1       0.0

In [109]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    # df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
    #               "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    df = pd.read_csv("assets/NISPUF17.csv", index_col = 0)
    df = df[['HAD_CPOX', 'P_NUMVRC']]
    df = df[df['HAD_CPOX'] < 3].dropna()
    
    column = ['had_chickenpox_column', 'num_chickenpox_vaccine_column']
    df.columns = column
    
    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    
    # YOUR CODE HERE
    return corr

In [110]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."
